---
- name: Install OSquery on Windows
  hosts: windows
  become: true

  tasks:
    - name: Install Chocolatey
      win_command: Set-ExecutionPolicy Bypass -Scope Process -Force; iex ((New-Object System.Net.WebClient).DownloadString('https://chocolatey.org/install.ps1')

  tasks:
    - name: Install OSQuery
    - win_command: choco install osquery --params='/InstallService'
  tasks:
    - name: Setup OSQuery
    - win_command: sc.exe create osqueryd type= own start= auto error= normal binpath= "C:Program Files/osquery/osqueryd/osqueryd.exe --flagfile=/Program Files/osquery/osquery.flags" displayname = 'osqueryd'
